jobs:
  test:
    executor:
      name: node/default
      tag: '12.16.2' # a node lts
    steps:
      - checkout
      - node/install-packages # install and cache
      - run:
          command: npm run test:ci
      - store_artifacts:
          path: .netlify
orbs:
  node: circleci/node@2.0.3
version: 2.1
workflows:
  test_grapdf:
    jobs:
      - test
